/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import Controladores.ControladorUsuarios;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author johan
 */
public class CambioDeContraseña extends javax.swing.JInternalFrame {
    ControladorUsuarios contr;

    public JRadioButton getRbtnMedico() {
        return RbtnMedico;
    }

    public void setRbtnMedico(JRadioButton RbtnMedico) {
        this.RbtnMedico = RbtnMedico;
    }

    public JRadioButton getRbtnSecretaria() {
        return RbtnSecretaria;
    }

    public void setRbtnSecretaria(JRadioButton RbtnSecretaria) {
        this.RbtnSecretaria = RbtnSecretaria;
    }

    public JLabel getLblExito() {
        return lblExito;
    }

    public void setLblExito(JLabel lblExito) {
        this.lblExito = lblExito;
    }

    public JTextField getTxtContraAntigua() {
        return txtContraAntigua;
    }

    public void setTxtContraAntigua(JTextField txtContraAntigua) {
        this.txtContraAntigua = txtContraAntigua;
    }

    public JTextField getTxtContraNueva() {
        return txtContraNueva;
    }

    public void setTxtContraNueva(JTextField txtContraNueva) {
        this.txtContraNueva = txtContraNueva;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }

    public JTextField getTxtVerificarContra() {
        return txtVerificarContra;
    }

    public void setTxtVerificarContra(JTextField txtVerificarContra) {
        this.txtVerificarContra = txtVerificarContra;
    }

    
    public CambioDeContraseña() {
        initComponents();
        this.getContentPane().setBackground(new Color(85, 151, 248));
        contr = new ControladorUsuarios();
        this.txtUsuario.setText(frmUsuarios.txtNombreUsuario.getText());
        if (frmUsuarios.cbUsuario.getSelectedItem() == "Medico") {
            this.RbtnMedico.setSelected(true);
        }
        if (frmUsuarios.cbUsuario.getSelectedItem() == "Secretaria") {
            this.RbtnSecretaria.setSelected(true);
        }
        this.lblExito.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtContraAntigua = new javax.swing.JTextField();
        txtContraNueva = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtVerificarContra = new javax.swing.JTextField();
        RbtnMedico = new javax.swing.JRadioButton();
        RbtnSecretaria = new javax.swing.JRadioButton();
        lblExito = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        txtContraAntigua.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña antigua", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        txtContraNueva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña nueva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        txtVerificarContra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Verificar Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        RbtnMedico.setText("Medico");

        RbtnSecretaria.setText("Secretaria");

        lblExito.setText("La contraseña fue cambiada");

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContraNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContraAntigua, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RbtnMedico)
                                .addGap(18, 18, 18)
                                .addComponent(RbtnSecretaria))
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExito, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVerificarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtContraAntigua, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContraNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RbtnMedico)
                            .addComponent(RbtnSecretaria)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblExito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVerificarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          if (RbtnSecretaria.isSelected()) {
            if (contr.cambioContraSec(this) == true) {
                lblExito.setVisible(true);
                lblExito.setForeground(Color.BLUE);
            } else {
                lblExito.setVisible(false);
            }
        }
        if (RbtnMedico.isSelected()) {
            if (contr.cambioContraMedic(this) == true) {
                lblExito.setVisible(true);
                lblExito.setForeground(Color.BLUE);
            } else {
                lblExito.setVisible(false);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtnMedico;
    private javax.swing.JRadioButton RbtnSecretaria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblExito;
    private javax.swing.JTextField txtContraAntigua;
    private javax.swing.JTextField txtContraNueva;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtVerificarContra;
    // End of variables declaration//GEN-END:variables
}
