/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import Modelo.ArchivoIniC;
import Modelo.BasedeDatos;

/**
 *
 * @author johan
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
         initComponents();
        //escritorio.setBorder(new ImagenFondo());
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.Exoedientes.setEnabled(false);
        this.RegistroCitas.setEnabled(false);
        this.RegistroPacientes.setEnabled(false);
        this.Usuario.setEnabled(false);
        String ruta = System.getProperty("user.dir");
        ArchivoIniC ini = new ArchivoIniC();
        ini.leerArchivo(ruta + "\\" + "Configuracion.ini");
        BasedeDatos bd = new BasedeDatos(ini.getProperties().getProperty("IP", "default value"), ini.getProperties().getProperty("Usuario", "default value"), ini.getProperties().getProperty("Pass", "default value"), ini.getProperties().getProperty("BD", "default value"), ruta);
        if (bd.comprobar().equals("Encendido")) {
            //estado.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accept-database-icon.png")));
            Exoedientes.setEnabled(true);
            Usuario.setEnabled(true);
            RegistroPacientes.setEnabled(true);
            RegistroCitas.setEnabled(true);
        } else {
            //estado.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/error-base-datos-wordpress.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ConectarBD = new javax.swing.JMenuItem();
        Usuario = new javax.swing.JMenuItem();
        RegistroPacientes = new javax.swing.JMenuItem();
        RegistroCitas = new javax.swing.JMenuItem();
        Exoedientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        ConectarBD.setText("Conectar al servidor");
        ConectarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarBDActionPerformed(evt);
            }
        });
        jMenu1.add(ConectarBD);

        Usuario.setText("Usuarios");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(Usuario);

        RegistroPacientes.setText("Pacientes");
        RegistroPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroPacientesActionPerformed(evt);
            }
        });
        jMenu1.add(RegistroPacientes);

        RegistroCitas.setText("Registro de citas");
        RegistroCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroCitasActionPerformed(evt);
            }
        });
        jMenu1.add(RegistroCitas);

        Exoedientes.setText("Expedientes");
        Exoedientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExoedientesActionPerformed(evt);
            }
        });
        jMenu1.add(Exoedientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConectarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarBDActionPerformed
        Servidor servidor = new Servidor();
        escritorio.add(servidor);
        servidor.show();
    }//GEN-LAST:event_ConectarBDActionPerformed

    private void RegistroCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroCitasActionPerformed
        Frm_Citas cita = new Frm_Citas();
        escritorio.add(cita);
        cita.show();
    }//GEN-LAST:event_RegistroCitasActionPerformed

    private void ExoedientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExoedientesActionPerformed
        InicioDeSesion sesion = new InicioDeSesion();
        escritorio.add(sesion);
        sesion.show();
    }//GEN-LAST:event_ExoedientesActionPerformed

    private void RegistroPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroPacientesActionPerformed
        frmPacientes pacientes = new frmPacientes();
        escritorio.add(pacientes);
        pacientes.show();
    }//GEN-LAST:event_RegistroPacientesActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        frmUsuarios usuarios = new frmUsuarios();
        escritorio.add(usuarios);
        usuarios.show();
    }//GEN-LAST:event_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConectarBD;
    private javax.swing.JMenuItem Exoedientes;
    private javax.swing.JMenuItem RegistroCitas;
    private javax.swing.JMenuItem RegistroPacientes;
    private javax.swing.JMenuItem Usuario;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
